services:
  - type: web
    name: cpp-memory-allocator-visualizer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
